### PR TITLE
Initialize German translation

### PR DESCRIPTION
**Pull request by ktutsch**
I translated the app and the F-Droid/Google Play store descriptions to German.

### CODE REVIEW

**Comment by ktutsch** [comment]
Some stuff I couldn't translate (the "Finish" button: no string and I couldn't find the code to make the label a string, the "Chance of X" is translated to "Xwahrscheinlichkeit" but the X is still english e. g. it has to be "Regenwahrscheinlichkeit" but it is "Rainwahrscheinlichkeit"). Any ideas how this could be fixed?

**Comment by TylerWilliamson** [comment]
Thank you for the work so far!

* The "Finish" text string is in my [TylerUtils](https://github.com/TylerWilliamson/TylerUtils) repository
* As for "Chance of X", the "Rain" is set in the code, but I will write a commit to make it use the strings xml instead

**Comment by TylerWilliamson** [comment]
I looked over the translations and everything looks good-to-go. Let me know if there are any final updates, otherwise I can merge this pull request now.

A few things to note:

1. German words are longer than English words, which may cause UI issues (for example on the Forecast activity), but I don't know a good way to fix this as the description is limited to just 2 lines in order for the card to be able to expand properly.
2. I will add your descriptions to the Google Play Store in the next release

**Comment by ktutsch** [comment]
All translations are done. Fixed some grammar errors and typos. This can be merged now.

**Comment by TylerWilliamson** [comment]
Thank you for the translation work! The code will be part of the next release!

**Pull request merged**
